class Prefecture < ActiveHash::Base
  include ActiveHash::Associations
  belongs_to :region

  self.data = [
    { "id": 1, "region_id": 1, "name": "北海道", "cities": ["札幌市", "函館市", "旭川市"] },
    { "id": 2, "region_id": 2, "name": "青森県", "cities": ["青森市", "弘前市", "八戸市"] },
    { "id": 3, "region_id": 2, "name": "岩手県", "cities": ["盛岡市", "宮古市", "一関市"] },
    { "id": 4, "region_id": 2, "name": "宮城県", "cities": ["仙台市", "石巻市", "塩竈市"] },
    { "id": 5, "region_id": 2, "name": "秋田県", "cities": ["秋田市", "横手市", "大館市"] },
    { "id": 6, "region_id": 2, "name": "山形県", "cities": ["山形市", "米沢市", "鶴岡市"] },
    { "id": 7, "region_id": 2, "name": "福島県", "cities": ["福島市", "郡山市", "いわき市"] },
    { "id": 8, "region_id": 3, "name": "茨城県", "cities": ["水戸市", "つくば市", "日立市"] },
    { "id": 9, "region_id": 3, "name": "栃木県", "cities": ["宇都宮市", "小山市", "栃木市"] },
    { "id": 10, "region_id": 3, "name": "群馬県", "cities": ["前橋市", "高崎市", "桐生市"] },
    { "id": 11, "region_id": 3, "name": "埼玉県", "cities": ["さいたま市", "川越市", "熊谷市"] },
    { "id": 12, "region_id": 3, "name": "千葉県", "cities": ["千葉市", "船橋市", "松戸市"] },
    { "id": 13, "region_id": 3, "name": "東京都", "cities": ["新宿区", "渋谷区", "品川区"] },
    { "id": 14, "region_id": 3, "name": "神奈川県", "cities": ["横浜市", "川崎市", "相模原市"] },
    { "id": 15, "region_id": 4, "name": "新潟県", "cities": ["新潟市", "長岡市", "上越市"] },
    { "id": 16, "region_id": 4, "name": "富山県", "cities": ["富山市", "高岡市", "魚津市"] },
    { "id": 17, "region_id": 4, "name": "石川県", "cities": ["金沢市", "七尾市", "小松市"] },
    { "id": 18, "region_id": 4, "name": "福井県", "cities": ["福井市", "敦賀市", "小浜市"] },
    { "id": 19, "region_id": 4, "name": "山梨県", "cities": ["甲府市", "富士吉田市", "甲斐市"] },
    { "id": 20, "region_id": 4, "name": "長野県", "cities": ["長野市", "松本市", "上田市"] },
    { "id": 21, "region_id": 4, "name": "岐阜県", "cities": ["岐阜市", "大垣市", "高山市"] },
    { "id": 22, "region_id": 4, "name": "静岡県", "cities": ["静岡市", "浜松市", "沼津市"] },
    { "id": 23, "region_id": 4, "name": "愛知県", "cities": ["名古屋市", "豊橋市", "岡崎市"] },
    { "id": 24, "region_id": 5, "name": "三重県", "cities": ["津市", "四日市市", "伊勢市"] },
    { "id": 25, "region_id": 5, "name": "滋賀県", "cities": ["大津市", "彦根市", "長浜市"] },
    { "id": 26, "region_id": 5, "name": "京都府", "cities": ["京都市", "舞鶴市", "宇治市"] },
    { "id": 27, "region_id": 5, "name": "大阪府", "cities": ["大阪市", "堺市", "東大阪市"] },
    { "id": 28, "region_id": 5, "name": "兵庫県", "cities": ["神戸市", "姫路市", "尼崎市"] },
    { "id": 29, "region_id": 5, "name": "奈良県", "cities": ["奈良市", "橿原市", "大和郡山市"] },
    { "id": 30, "region_id": 5, "name": "和歌山県", "cities": ["和歌山市", "田辺市", "新宮市"] },
    { "id": 31, "region_id": 6, "name": "鳥取県", "cities": ["鳥取市", "米子市", "倉吉市"] },
    { "id": 32, "region_id": 6, "name": "島根県", "cities": ["松江市", "出雲市", "浜田市"] },
    { "id": 33, "region_id": 6, "name": "岡山県", "cities": ["岡山市", "倉敷市", "津山市"] },
    { "id": 34, "region_id": 6, "name": "広島県", "cities": ["広島市", "福山市", "呉市"] },
    { "id": 35, "region_id": 6, "name": "山口県", "cities": ["山口市", "下関市", "宇部市"] },
    { "id": 36, "region_id": 7, "name": "徳島県", "cities": ["徳島市", "鳴門市", "阿南市"] },
    { "id": 37, "region_id": 7, "name": "香川県", "cities": ["高松市", "丸亀市", "坂出市"] },
    { "id": 38, "region_id": 7, "name": "愛媛県", "cities": ["松山市", "今治市", "宇和島市"] },
    { "id": 39, "region_id": 7, "name": "高知県", "cities": ["高知市", "室戸市", "安芸市"] },
    { "id": 40, "region_id": 8, "name": "福岡県", "cities": ["福岡市", "北九州市", "久留米市"] },
    { "id": 41, "region_id": 8, "name": "佐賀県", "cities": ["佐賀市", "唐津市", "鳥栖市"] },
    { "id": 42, "region_id": 8, "name": "長崎県", "cities": ["長崎市", "佐世保市", "島原市"] },
    { "id": 43, "region_id": 8, "name": "熊本県", "cities": ["熊本市", "八代市", "人吉市"] },
    { "id": 44, "region_id": 8, "name": "大分県", "cities": ["大分市", "別府市", "中津市"] },
    { "id": 45, "region_id": 8, "name": "宮崎県", "cities": ["宮崎市", "都城市", "延岡市"] },
    { "id": 46, "region_id": 8, "name": "鹿児島県", "cities": ["鹿児島市", "鹿屋市", "枕崎市"] },
    { "id": 47, "region_id": 9, "name": "沖縄県", "cities": ["那覇市", "宜野湾市", "石垣市"] }
  ]
end
